erDiagram
    %% MODULE: account
    user {
        uuidv7 id PK
        varchar email UK "cite: 2"
        varchar password_hash
        varchar name
        char wallet_address UK
        varchar status "cite: 3"
        boolean two_factor_enabled
        uuidv7 user_id FK "cite: 5"
    }
    device {
        uuidv7 id PK
        varchar platform "cite: 4"
        varchar push_token
        boolean is_active
        uuidv7 user_id FK "cite: 5"
    }
    login {
        uuidv7 id PK
        inet ip "cite: 6"
        boolean success
        uuidv7 user_id FK
    }

    %% MODULE: catalog
    asset {
        varchar id PK "cite: 9"
        varchar symbol
        varchar network "cite: 9"
        boolean is_active
    }
    strategy {
        varchar id PK "cite: 10"
        text description "cite: 11"
        decimal expected_apy_range_low
    }

    %% MODULE: portfolio
    investment {
        uuidv7 id PK
        varchar strategy_id FK "cite: 12"
        varchar asset_id FK
        decimal amount_usd
        varchar status "cite: 13"
        uuidv7 user_id FK "cite: 17"
    }
    earning {
        uuidv7 id PK
        decimal amount "cite: 16"
        uuidv7 investment_id FK
    }

    %% MODULE: treasury
    withdrawal {
        uuidv7 id PK
        decimal amount_usd
        varchar status "Ex: PENDING, COMPLETED, FAILED"
        char transaction_hash
        timestamp created_at
        uuidv7 user_id FK
    }

    %% MODULE: communication
    notification {
        uuidv7 id PK
        varchar title "cite: 7"
        boolean is_read
        uuidv7 user_id FK
    }

    %% MODULE: system
    config {
        varchar key PK "cite: 8"
        text value "cite: 8"
    }

    user ||--o{ device : "has"
    user ||--o{ login : "logs"
    user ||--o{ notification : "receives"
    user ||--o{ investment : "owns" "cite: 17"
    user ||--o{ withdrawal : "requests"
    strategy ||--o{ investment : "defines"
    asset ||--o{ investment : "denominates"
    investment ||--o{ earning : "generates"